<?php

/*!
 * https://raccoonsquare.com
 * raccoonsquare@gmail.com
 *
 * Copyright 2012-2021 Demyanchuk Dmitry (raccoonsquare@gmail.com)
 */

if (!defined("APP_SIGNATURE")) {

    header("Location: /");
    exit;
}

$C['FILE_IMAGE_MAX_UPLOAD_SIZE'] = 3145728;
$C['FILE_VIDEO_MAX_UPLOAD_SIZE'] = 7340035;

$C['BONUS_SIGNUP'] = 10; // bonus for registration in credits
$C['BONUS_REFERRAL'] = 5; // bonus for registration referral in credits

$C['UPGRADES_GHOST_MODE_COST'] = 150;
$C['UPGRADES_VERIFIED_BADGE_COST'] = 100;
$C['UPGRADES_DISABLE_ADS_COST'] = 200;

$C['POST_MAX_IMAGES_COUNT'] = 7;
$C['API_VERSION'] = "v2";

$C['GCM_NOTIFY_PROFILE_PHOTO_APPROVE'] = 1003;
$C['GCM_NOTIFY_PROFILE_PHOTO_REJECT'] = 1004;
$C['GCM_NOTIFY_PROFILE_COVER_APPROVE'] = 1007;
$C['GCM_NOTIFY_PROFILE_COVER_REJECT'] = 1008;

$C['NOTIFY_TYPE_PROFILE_PHOTO_APPROVE'] = 2003;
$C['NOTIFY_TYPE_PROFILE_PHOTO_REJECT'] = 2004;
$C['NOTIFY_TYPE_PROFILE_COVER_APPROVE'] = 2007;
$C['NOTIFY_TYPE_PROFILE_COVER_REJECT'] = 2008;

$C['IMAGE_TYPE_PROFILE_PHOTO'] = 0;
$C['IMAGE_TYPE_PROFILE_COVER'] = 1;

$C['APP_TYPE_ALL'] = -1;
$C['APP_TYPE_MANAGER'] = 0;
$C['APP_TYPE_WEB'] = 1;
$C['APP_TYPE_ANDROID'] = 2;
$C['APP_TYPE_IOS'] = 3;

$C['GALLERY_ITEM_TYPE_IMAGE'] = 0;
$C['GALLERY_ITEM_TYPE_VIDEO'] = 1;

$C['REPORT_TYPE_ITEM'] = 0;
$C['REPORT_TYPE_PROFILE'] = 1;
$C['REPORT_TYPE_MESSAGE'] = 2;
$C['REPORT_TYPE_COMMENT'] = 3;
$C['REPORT_TYPE_GALLERY_ITEM'] = 4;
$C['REPORT_TYPE_MARKET_ITEM'] = 5;
$C['REPORT_TYPE_COMMUNITY'] = 6;

$C['ITEM_TYPE_IMAGE'] = 0;
$C['ITEM_TYPE_VIDEO'] = 1;
$C['ITEM_TYPE_POST'] = 2;
$C['ITEM_TYPE_COMMENT'] = 3;
$C['ITEM_TYPE_GALLERY'] = 4;

// Payments

// PA - PAYMENT ACTION
$C['PA_BUY_CREDITS'] = 0;
$C['PA_BUY_GIFT'] = 1;
$C['PA_BUY_VERIFIED_BADGE'] = 2;
$C['PA_BUY_GHOST_MODE'] = 3;
$C['PA_BUY_DISABLE_ADS'] = 4;
$C['PA_BUY_REGISTRATION_BONUS'] = 5;
$C['PA_BUY_REFERRAL_BONUS'] = 6;
$C['PA_BUY_MANUAL_BONUS'] = 7;
$C['PA_BUY_PRO_MODE'] = 8;
$C['PA_BUY_SPOTLIGHT'] = 9;
$C['PA_BUY_MESSAGE_PACKAGE'] = 10;

// PT - PAYMENT TYPE
$C['PT_UNKNOWN'] = 0;
$C['PT_CREDITS'] = 1;
$C['PT_CARD'] = 2;
$C['PT_GOOGLE_PURCHASE'] = 3;
$C['PT_APPLE_PURCHASE'] = 4;
$C['PT_ADMOB_REWARDED_ADS'] = 5;
$C['PT_BONUS'] = 6;

$C['CURRENCY_USD'] = 0;
$C['CURRENCY_EUR'] = 1;

// ERROR CODES

$C['ERROR_LOGIN_TAKEN'] = 300;
$C['ERROR_EMAIL_TAKEN'] = 301;
$C['ERROR_FACEBOOK_ID_TAKEN'] = 302;
$C['ERROR_PHONE_TAKEN'] = 303;

$C['ERROR_ACCOUNT_ID'] = 400;

$C['ERROR_FILE_SIZE_BIG'] = 501;
$C['ERROR_FILE_SIZE_SMALL'] = 502;

$C['ERROR_IMAGE_FILE_FORMAT'] = 503;
$C['ERROR_IMAGE_FILE_WIDTH_HEIGHT'] = 504;

$C['ERROR_CLIENT_ID'] = 19100;
$C['ERROR_CLIENT_SECRET'] = 19101;